### ISSUE TITLE
Why not use History.js?

### ISSUE THREAD

**Issue by balupton** [millermedeiros/Hasher#21]
It seems [History.js](http://github.com/balupton/history.js) is doing the same thing as your project? Is there anyway anything missing from History.js that you need, as I'll be glad to extend it for your use cases :)

PS. Awesome logo!

**Comment by millermedeiros** [comment]
this project was created before History.js existed (first commits are from 04/2010), I didn't followed the history push/pop states because it only makes sense to use those features if you're going to implement a fallback on the server-side (basically if you are using it as an enhancement for static pages), the intention of Hasher is to stay solely on the client-side and to be used on applications that can't work without JS and flash websites.

The original intention was to be a replacement to [SWFAddress](http://www.asual.com/swfaddress/) for Flash websites, but until now I didn't spent time writing documentation and/or advertised it, but I'm already using it on a few projects tho.

Cheers.
