### ISSUE TITLE
Add Hasher to npm/ender

### ISSUE THREAD

**Issue by ovaillancourt** [millermedeiros/Hasher#36]
Hi there!

First of all, great lib!

It would be nice if it was made available on npm/ender. Crossroads and signals already are, given that Hasher works hand in hand with them, it would be a logical move to make ender package building easier :).

Thanks!

**Comment by millermedeiros** [comment]
uhm, I haven't added it to npm because Hasher doesn't work on nodejs.. I haven't used ender yet (since I'm using RequireJS on almost all my projects), to make it work with ender we need to [update the wrapper](https://github.com/millermedeiros/Hasher/blob/master/dev/src/wrapper.js) to be similar to [crossroads wrapper](https://github.com/millermedeiros/crossroads.js/blob/master/dev/src/wrapper.js).

I probably won't have free time to do it this week - specially since I never used ender and will need some time to read docs, install, test, etc..

thx

**Comment by ovaillancourt** [comment]
Got you! I agree with npm, it's mostly oriented towards nodejs stuff. Given that ender is actually built on top of npm and uses its package directory, I wonder what's the stance for pure browser-side libs like hasher.

Ender is a breeze to use, I can really recommend it :). 

Anyway, it's nothing too pressing, but it would definitely be a nice to have, I found the hasher/crossroads lib to be very easy to use combined with ender's jeesh :).

Thanks and keep up the good work!

**Comment by millermedeiros** [comment]
Ignoring this for now, don't think it's a good idea to keep a browser-only lib on npm, may cause confusions. Thanks for reporting and sorry for not doing it.

**Comment by ovaillancourt** [comment]
Alright, thanks for following up!

As a reference if you reconsider the option at some point:
http://groups.google.com/group/npm-/browse_thread/thread/26023ba9df865893#

**Comment by millermedeiros** [comment]
added hasher to npm, see #52 - I guess a lot of people been using npm nowadays even for front-end.
