### ISSUE TITLE
hasher.reload ?

### ISSUE THREAD

**Issue by gaiottino** [millermedeiros/Hasher#40]
Hi,

What's the best way to reload the current hash? hasher.replace(hasher.getHash()) doesn't work. I want to rerender the current route without a page reload after an ajax-request has completed.

Thanks

**Comment by millermedeiros** [comment]
trying to set the hash value to the same value as the current one won't trigger a `changed` signal (since the value didn't changed). You can manually dispatch the `changed` event by calling: `hasher.changed.dispatch(hasher.getHash())`, or if you are using it together with crossroads you can call `crossroads.parse(hasher.getHash())`.

Does it solve your problem?

**Comment by gaiottino** [comment]
crossroads.parse worked nicely. Thanks!
