### ISSUE TITLE
Failure to identify as _isLegacyIE in IE 7 IE 7 Standards doc mode

### ISSUE THREAD

**Issue by mbbender** [millermedeiros/Hasher#46]
I'm not sure why it's failing yet, but I did come across this comment on stack overflow: @xkit explained to me a good feature test to work around the fact that although IE7 doesn't support onhashchange it would still return true for existence inference such as if("onhashchange" in window){/code/} when using IE7 Standard Document Mode in IE8.

It is indeed identifying my IE7 app as supporting Hash Change, although its not working.

**Comment by mbbender** [comment]
Surely not pretty, but I added this and it worked for me.
_isHashChangeSupported = ('onhashchange' in window) && !(navigator.appVersion.substr(navigator.appVersion.indexOf("MSIE"),8) == "MSIE 7.0")

**Comment by millermedeiros** [comment]
You can use `document.documentMode != 7` to check if it is not compatibility mode. I plan to release a new version soon (probably next week) that fixes this problem, it just takes a while since I need to test the changes in multiple browsers and been busy with other projects.

Closing this report in favor of #44. Thanks!

**Comment by millermedeiros** [comment]
I will do a v1.1.1 release today with a fix.
