### ISSUE TITLE
Is there a way to implement "onChange" that fires before "changed"? 

### ISSUE THREAD

**Issue by goosechaser** [millermedeiros/Hasher#55]
Hi. Is there a way process ALL hash changes before the browser sets the hash? Right now I  use the following function:

```
function parseHash(newHash, oldHash){

hasher.prependHash = '!/';
hasher.replaceHash(newHash);
}
```

It works but the hash flashes for an instant (mere ms.) in the URL bar; that is, first the original hash is set (e.g., "#25") and then it is prepended and replaced (e.g., "#!/25").

Thanks.

**Comment by millermedeiros** [comment]
the problem is that the hash value can be set manually by the user or triggered by regular links `<a href="#foo">foo</a>`. there is not way to intercept the browser event before the `hashchange` event is triggered by the browser (which takes a few ms).

`hasher,prependHash` only works for hashes that are set programmatically.
